# Generated by Django 3.2.5 on 2021-08-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=10, null=True)),
                ('category', models.CharField(choices=[('indoor', 'Indoor'), ('Kitchen', 'Kitchen'), ('outdoor', 'OutDoor')], max_length=20, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
