# Generated by Django 3.2.5 on 2021-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('OutforDelivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=20),
        ),
    ]
